version: '2'
services:
  db:
    image: postgres
    container_name: docpg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=doctor
      - RAILS_ENV=${RAILS_ENV}
    volumes: 
      - doctor_db:/var/lib/postgresql/data

  web:
    image: minio/doctor
    container_name: docapp
    depends_on:
      - db
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_URL=postgresql://postgres:postgres@db/doctor?pool=5
      - IS_DOCKER=true
      - CONSOLE_IP_WHITELIST
    ports:
      - "3000:3000"

volumes:
  doctor_db:
